<h2>Copy this link</h2>
<div>
    <p>Hello <?= $block->getName()?></p>
    <p>
        You have a pinned to your email - <?= $block->getEmail()?>  link for a discount coupon for each of your friends.
    </p>
    <p>
        Just copy and send to all your friends!
        If anyone of them will use use your link generated coupon to purchase something from us,
        than you will receive even bigger discount
    </p>
</div>
<div>
    <a href="<?= $block->getLink()?>">
        <?= $block->getLink()?>
    </a>
</div>